### ISSUE TITLE
Change to 'About'

### ISSUE THREAD

**Issue by AdamHibberd** [JustinWingChungHui/OITS_3d#5]
This line:

The Optical Interplanetary Trajectory Software is software that find the most optimized trajectory between bodies in the solar system to reduce the amount of fuel needed.

Should be changed to:

The Optimum Interplanetary Trajectory Software (OITS) is software that finds the optimum trajectory between user-specified sequence of celestial bodies. 'Optimum' is in the sense of minimum ∆V, equivalent to minimising fuel usage.

**Comment by JustinWingChungHui** [comment]
Updated and deployed
