### ISSUE TITLE
I'm for the rights of users to abort

### ISSUE THREAD

**Issue by AdamHibberd** [JustinWingChungHui/OITS_3d#7]
I think there should be an option for the user to abort OITS just so they can see where the software has got to.
When running OITS from Linux this is achieved by typing Control-C in the output window. The software just outputs the best solution it has found so far. If there is a way of doing this on the web UI, that would be great.

**Comment by JustinWingChungHui** [comment]
It can definitely be terminated.  I'll have to see if it outputs the files

**Comment by JustinWingChungHui** [comment]
Done
